set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN AK17 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]

set_property PACKAGE_PIN V33  [get_ports hdmi_clk]
set_property PACKAGE_PIN Y30 [get_ports {hdmi_d[0]}]
set_property PACKAGE_PIN Y33 [get_ports {hdmi_d[1]}]
set_property PACKAGE_PIN Y32 [get_ports {hdmi_d[2]}]
set_property PACKAGE_PIN W33 [get_ports {hdmi_d[3]}]
set_property PACKAGE_PIN W34 [get_ports {hdmi_d[4]}]
set_property PACKAGE_PIN W31 [get_ports {hdmi_d[5]}]
set_property PACKAGE_PIN Y31 [get_ports {hdmi_d[6]}]
set_property PACKAGE_PIN V34 [get_ports {hdmi_d[7]}]
set_property PACKAGE_PIN V32 [get_ports {hdmi_d[8]}]
set_property PACKAGE_PIN U34 [get_ports {hdmi_d[9]}]
set_property PACKAGE_PIN V31 [get_ports {hdmi_d[10]}]
set_property PACKAGE_PIN W30 [get_ports {hdmi_d[11]}]
set_property PACKAGE_PIN W29 [get_ports {hdmi_d[12]}]
set_property PACKAGE_PIN V29 [get_ports {hdmi_d[13]}]
set_property PACKAGE_PIN W28 [get_ports {hdmi_d[14]}]
set_property PACKAGE_PIN V28 [get_ports {hdmi_d[15]}]
set_property PACKAGE_PIN V27 [get_ports {hdmi_d[16]}]
set_property PACKAGE_PIN W26 [get_ports {hdmi_d[17]}]
set_property PACKAGE_PIN V26 [get_ports {hdmi_d[18]}]
set_property PACKAGE_PIN U27 [get_ports {hdmi_d[19]}]
set_property PACKAGE_PIN U26 [get_ports {hdmi_d[20]}]
set_property PACKAGE_PIN U25 [get_ports {hdmi_d[21]}]
set_property PACKAGE_PIN U24 [get_ports {hdmi_d[22]}]
set_property PACKAGE_PIN Y22 [get_ports {hdmi_d[23]}]
set_property PACKAGE_PIN AA33 [get_ports hdmi_de]
set_property PACKAGE_PIN Y28 [get_ports hdmi_hs]
set_property PACKAGE_PIN AE31 [get_ports hdmi_vs]
set_property PACKAGE_PIN R22 [get_ports hdmi_scl]
set_property PACKAGE_PIN R21 [get_ports hdmi_sda]

set_property IOSTANDARD LVCMOS18 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS18 [get_ports hdmi_sda]
set_property IOSTANDARD LVCMOS18 [get_ports {hdmi_d[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS18 [get_ports hdmi_de]
set_property IOSTANDARD LVCMOS18 [get_ports hdmi_vs]
set_property IOSTANDARD LVCMOS18 [get_ports hdmi_hs]

set_property PULLUP true [get_ports hdmi_scl]
set_property PULLUP true [get_ports hdmi_sda]

set_property SLEW FAST [get_ports {hdmi_d[*]}]
set_property DRIVE 8 [get_ports {hdmi_d[*]}]
set_property SLEW FAST [get_ports hdmi_clk]
set_property SLEW FAST [get_ports hdmi_de]
set_property SLEW FAST [get_ports hdmi_hs]
set_property SLEW FAST [get_ports hdmi_scl]
set_property SLEW FAST [get_ports hdmi_sda]
set_property SLEW FAST [get_ports hdmi_vs]