# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/imports/example_ibert_sfp_12_5g.xdc

# XDC: D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/imports/ibert_ultrascale_gth_ip_example.xdc

# XDC: new/sfpp.xdc

# IP: ip/ibert_sfp_12_5g/ibert_sfp_12_5g.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ibert_sfp_12_5g || ORIG_REF_NAME==ibert_sfp_12_5g} -quiet] -quiet
