# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/XilinxPrj/AXU7EV/eth_logic_ku040_full/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
# IP: The module: 'udp_checksum_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU7EV/eth_logic_ku040_full/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_checksum_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU7EV/eth_logic_ku040_full/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_checksum_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/XilinxPrj/AXU7EV/eth_logic_ku040_full/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
# IP: The module: 'udp_checksum_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXU7EV/eth_logic_ku040_full/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_checksum_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/XilinxPrj/AXU7EV/eth_logic_ku040_full/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_checksum_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
