# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc

# IP: ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet
