# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.cache/wt [current_project]
set_property parent.project_path e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_wrapper_functions.v
set_property file_type "Verilog Header" [get_files e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_wrapper_functions.v]
read_verilog -library xil_defaultlib {
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_bit_sync.v
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_rx.v
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_tx.v
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_init.v
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_reset_sync.v
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.v
  e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_wrapper.v
  E:/ax/ku040/gtwizard_ultrascale_0_ex/src/packet_rec.v
  E:/ax/ku040/gtwizard_ultrascale_0_ex/src/packet_send.v
  E:/ax/ku040/gtwizard_ultrascale_0_ex/src/word_align.v
  E:/ax/ku040/gtwizard_ultrascale_0_ex/src/top.v
}
read_ip -quiet e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc]

read_ip -quiet E:/ax/ku040/gtwizard_ultrascale_0_ex/src/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/ila_0/ila_0_ooc.xdc]

read_ip -quiet E:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock.xci
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock_board.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock_ooc.xdc]

read_ip -quiet e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xci
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku040/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc
set_property used_in_implementation false [get_files e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
