# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.cache/wt [current_project]
set_property parent.project_path F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/color_bar.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/i2c_master/i2c_config.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/i2c_master/timescale.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/i2c_master/i2c_master_defines.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/i2c_master/i2c_master_bit_ctrl.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/i2c_master/i2c_master_byte_ctrl.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/i2c_master/i2c_master_top.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/lut_adv7511.v
  F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/top.v
}
read_ip -quiet F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all f:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all f:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/constrs_1/new/hdmi_output_test.xdc
set_property used_in_implementation false [get_files F:/intel_project/AX7Z035/course_s1/02_hdmi_out_test/hdmi_out_test.srcs/constrs_1/new/hdmi_output_test.xdc]


synth_design -top top -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
