set_property SRC_FILE_INFO {cfile:e:/ax/ku040/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc rfile:../../../imports/gtwizard_ultrascale_0_example_top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin AF5 [get_ports mgtrefclk0_x0y0_n]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin AF6 [get_ports mgtrefclk0_x0y0_p]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk_freerun -period 33.333 [get_ports hb_gtwiz_reset_clk_freerun_in]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk_mgtrefclk0_x0y0_p -period 8.0 [get_ports mgtrefclk0_x0y0_p]
