# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/XilinxPrj/AXUK40/gt_test_12p5g/gth_ex/gth_ex.srcs/sources_1/ip/gth/gth.xci
# IP: The module: 'gth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXUK40/gt_test_12p5g/gth_ex/gth_ex.srcs/sources_1/ip/gth/synth/gth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gth'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXUK40/gt_test_12p5g/gth_ex/gth_ex.srcs/sources_1/ip/gth/synth/gth.xdc
# XDC: The top module name and the constraint reference have the same name: 'gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/XilinxPrj/AXUK40/gt_test_12p5g/gth_ex/gth_ex.srcs/sources_1/ip/gth/gth.xci
# IP: The module: 'gth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxPrj/AXUK40/gt_test_12p5g/gth_ex/gth_ex.srcs/sources_1/ip/gth/synth/gth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/XilinxPrj/AXUK40/gt_test_12p5g/gth_ex/gth_ex.srcs/sources_1/ip/gth/synth/gth.xdc
# XDC: The top module name and the constraint reference have the same name: 'gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
