# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/ax/ku040/13_ddr_test/ddr4_0_ex/imports/example_design.xdc

# IP: ip/ddr4_0/ddr4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_0 || ORIG_REF_NAME==ddr4_0} -quiet] -quiet
