# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_10g/ibert_sfp_10g_ex/imports/example_ibert_sfp_10g.xdc

# XDC: d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_10g/ibert_sfp_10g_ex/imports/ibert_ultrascale_gth_ip_example.xdc

# XDC: new/sfp.xdc

# IP: ip/ibert_sfp_10g/ibert_sfp_10g.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ibert_sfp_10g || ORIG_REF_NAME==ibert_sfp_10g} -quiet] -quiet
