# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.cache/wt [current_project]
set_property parent.project_path D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/imports/example_ibert_sfp_12_5g.v
read_ip -quiet D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/ibert_sfp_12_5g.xci
set_property is_enabled false [get_files -all D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/data/mb_bootloop_le.elf]
set_property is_enabled false [get_files -all D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/synth/ibert_sfp_12_5g_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/synth/ibert_sfp_12_5g.xdc]
set_property used_in_implementation false [get_files -all d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/synth/sw_mcs_all.xdc]
set_property used_in_implementation false [get_files -all d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/sources_1/ip/ibert_sfp_12_5g/synth/attributes.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/imports/example_ibert_sfp_12_5g.xdc
set_property used_in_implementation false [get_files D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/imports/example_ibert_sfp_12_5g.xdc]

read_xdc D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/constrs_1/new/sfpp.xdc
set_property used_in_implementation false [get_files D:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_12_5g/ibert_sfp_12_5g_ex/ibert_sfp_12_5g_ex.srcs/constrs_1/new/sfpp.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top example_ibert_sfp_12_5g -part xcku040-ffva1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef example_ibert_sfp_12_5g.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file example_ibert_sfp_12_5g_utilization_synth.rpt -pb example_ibert_sfp_12_5g_utilization_synth.pb"
