# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock.xci
# IP: The module: 'sys_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock.xci
# IP: The module: 'sys_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/ax/ku040/gtwizard_ultrascale_0_ex/src/sys_clock/sys_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
