# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/sd_bbmmpp/constrs_1/new/sd_picture_hdmi.xdc

# IP: E:/sd_bbmmpp/sources_1/ip/ddr4_0/ddr4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_0 || ORIG_REF_NAME==ddr4_0} -quiet] -quiet

# IP: E:/sd_bbmmpp/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_64i_32o_128 || ORIG_REF_NAME==afifo_64i_32o_128} -quiet] -quiet

# IP: E:/sd_bbmmpp/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_32i_64o_256 || ORIG_REF_NAME==afifo_32i_64o_256} -quiet] -quiet

# IP: E:/sd_bbmmpp/sources_1/ip/video_pll/video_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_pll || ORIG_REF_NAME==video_pll} -quiet] -quiet

# IP: E:/sd_bbmmpp/sources_1/ip/clk_ref/clk_ref.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_ref || ORIG_REF_NAME==clk_ref} -quiet] -quiet
