set_property SRC_FILE_INFO {cfile:d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_10g/ibert_sfp_10g_ex/imports/example_ibert_sfp_10g.xdc rfile:../../../imports/example_ibert_sfp_10g.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:d:/xilinx_fpga/ku040/sfp_ibert/ibert_sfp_10g/ibert_sfp_10g_ex/ibert_sfp_10g_ex.srcs/constrs_1/new/sfp.xdc rfile:../../../ibert_sfp_10g_ex.srcs/constrs_1/new/sfp.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 125000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF6 [get_ports gth_refclk0p_i[0]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports gth_refclk0n_i[0]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD6 [get_ports gth_refclk1p_i[0]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5 [get_ports gth_refclk1n_i[0]]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM10 [get_ports  {disable1[0]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL10 [get_ports  {disable1[1]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP9 [get_ports  {disable1[2]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN9 [get_ports  {disable1[3]}]
